//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//     </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System; 
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Car_Id { get; set; }
        public string Car_Name { get; set; }
        public Nullable<int> NumOfSeats { get; set; }
        public Nullable<int> Car_Category { get; set; }
        public string Car_Color { get; set; }
        public Nullable<int> Car_Since { get; set; }
        public string Car_From { get; set; }
    

        public virtual Company Company { get; set; }
    }
}
